/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.xapuka.withbuilder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WithBuilderProcessorTest {
    @Test void someLibraryMethodReturnsTrue() {
        WithBuilderProcessor classUnderTest = new WithBuilderProcessor();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
